if (UNIX)
    find_package(PkgConfig REQUIRED)
endif()

add_library(roar-cryptopp INTERFACE)

if (WIN32)
    find_package(CryptoPP REQUIRED)
    if (${MSVC})
        target_link_libraries(roar-cryptopp INTERFACE cryptopp::cryptopp)
    else()
        target_link_libraries(roar-cryptopp INTERFACE cryptopp-static)
    endif()
elseif(APPLE)
    find_library(CRYPTOPP_LIB libcryptopp.a HINTS /opt/homebrew/lib)
    target_include_directories(roar-cryptopp INTERFACE /opt/homebrew/include)
    target_link_libraries(roar-cryptopp INTERFACE ${CRYPTOPP_LIB})
elseif(UNIX)
    pkg_check_modules(cryptopp IMPORTED_TARGET libcrypto++)
    if ("${cryptopp_FOUND}" STREQUAL "1")
    else()
        pkg_check_modules(cryptopp IMPORTED_TARGET libcryptopp)
    endif()
    target_link_libraries(roar-cryptopp INTERFACE PkgConfig::cryptopp)
endif()